Iter13
k0st1a/metrics pull request #12
Opened 2024-03-18 14:53 UTC by k0st1a

## Итерация #10

Сервер:
* Добавьте функциональность подключения к базе данных. В качестве СУБД используйте PostgreSQL не ниже 10 версии.
* Добавьте в сервер хендлер GET /ping, который при запросе проверяет соединение с базой данных. При успешной проверке хендлер должен вернуть HTTP-статус 200 OK, при неуспешной — 500 Internal Server Error.

Строка с адресом подключения к БД должна получаться из переменной окружения DATABASE_DSN или флага командной строки -d.

Для работы с БД используйте один из следующих пакетов:
* database/sql,
* github.com/jackc/pgx,
* github.com/lib/pq,
* github.com/jmoiron/sqlx.

## Итерация #11

Перепишите сервер для сбора метрик таким образом, чтобы СУБД PostgreSQL стала хранилищем метрик вместо текущей реализации.

Сервису нужно самостоятельно создать все необходимые таблицы в базе данных. Схема и формат хранения остаются на ваше усмотрение.

Для хранения значений gauge рекомендуется использовать тип double precision.

При отсутствии переменной окружения DATABASE_DSN или флага командной строки -d или при их пустых значениях вернитесь последовательно к:
* хранению метрик в файле при наличии соответствующей переменной окружения или флага командной строки;
* хранению метрик в памяти.

## Итерация #12

Сервер:
* Добавьте новый хендлер POST /updates/, принимающий в теле запроса множество метрик в формате: []Metrics (списка метрик).

Агент:
* Научите агент работать с использованием нового API (отправлять метрики батчами).

Стоит помнить, что:
* нужно соблюдать обратную совместимость;
* отправлять пустые батчи не нужно;
* вы умеете сжимать контент по алгоритму gzip;
* изменение в базе можно выполнять в рамках одной транзакции или одного запроса;
* необходимо избегать формирования условий для возникновения состояния гонки (race condition).

## Итерация #13

Добавьте обработку retriable-ошибок.

Retriable-ошибки — это ошибки, которые могут быть исправлены повторной попыткой выполнения операции. Это бывает полезно для программ, которые работают с сетью или файловой системой, где возможны временные проблемы связи или доступа к данным. Ошибки могут быть вызваны различными причинами, такими как перегрузка сервера, недоступность сети или ошибки в коде программы.

Примеры retriable-ошибок:
* Ошибка связи с сервером при отправке запроса.
* Ошибка чтения данных из сети или БД из-за проблем соединения.
* Ошибка доступа к файлу, который был заблокирован другим процессом.

Сценарии возможных ошибок:
* Агент не сумел с первой попытки выгрузить данные на сервер из-за временной невозможности установить соединение с сервером.
* При обращении к PostgreSQL cервер получил ошибку транспорта (из категории Class 08 — Connection Exception).

* Стратегия реализации:
* Количество повторов должно быть ограничено тремя дополнительными попытками.
* Интервалы между повторами должны увеличиваться: 1s, 3s, 5s.
* Чтобы определить тип ошибки PostgreSQL, с которой завершился запрос, можно воспользоваться библиотекой `github.com/jackc/pgerrcode`, в частности `pgerrcode.UniqueViolation`.

2024-03-18 23:39 UTC, valentinsoe requested changes
Спасибо за работу.
1) Код предыдущих инкрементов не проверял

В целом меня все устраивает, критических замечаний нет, кроме организации повторов операций. Рекомендую подумать, как можно написать универсальный механизм не привязанный ни к БД, ни к другим пакетам. Просто код универсально повторяющий вызов любой функции в зависимости от возвращаемой ей ошибки.

2024-03-18 23:39 UTC, valentinsoe commented on internal/handlers/json/handlers.go
> +	ct := r.Header.Get(headerContentType)
Не нужно переделывать, но можно 1 раз написать middleware(параметризуемую Content-Type) и не писать это в коде каждого отдельного хендлера

2024-03-18 23:39 UTC, valentinsoe commented on internal/handlers/json/handlers.go
> +	defer func() {
Не совсем понял зачем это. Например следующая ощибка(на строчке 77) появится в логе дважды

2024-03-18 23:39 UTC, valentinsoe commented on internal/handlers/json/handlers.go
> +	ctx := r.Context()
Мое занудство(я вообще зануда, не значит что надо весь мой гундеж исправлять :) ) Но во-первых можно при вызове функции использовать r.Context().
А во-вторых мы его тут объявили, потом написали 20-30 строчек кода к нему не относящихся, а потом им воспользовались:)

2024-03-18 23:39 UTC, valentinsoe commented on internal/models/model.go
> +func Deserialize2(b []byte) ([]Metrics, error) {
DeserializeList(slice, array)? Почему 2?

2024-03-18 23:39 UTC, valentinsoe commented on internal/storage/db/retry/request.go
> +		if isConnectionException(err) {
Рекомендую написать общий "ретрай", который не привязан к БД. И который реализован таким образом, чтобы его реализацию не приходилось копировать в каждую функцию.
Чтобы в нем можно было вызвать функцию. А для возврата значений использовать замыкания.

2024-03-19 14:37 UTC, k0st1a commented on internal/models/model.go
> +func Deserialize2(b []byte) ([]Metrics, error) {
Были трудности с сериализацией/десериализацией `[]Metrics` в easyjson. Поэтому написал тестовые функции с использованием `encoding/json`, на случай не получиться сделать через easyjson. А когда через easyjson удалось сделать  сериализацию/десериализацию `[]Metrics`, про тестовые функции забыл. Удалю их.

2024-03-19 18:47 UTC, k0st1a commented on internal/handlers/json/handlers.go
> +	defer func() {
Удалил.

2024-03-19 18:57 UTC, k0st1a commented on internal/handlers/json/handlers.go
> +	ctx := r.Context()
> Мое занудство(я вообще зануда, не значит что надо весь мой гундеж исправлять :) ) Но во-первых можно при вызове функции использовать r.Context().

Поправил.

2024-03-19 18:58 UTC, k0st1a commented on internal/storage/db/retry/request.go
> +		if isConnectionException(err) {
Написал.

2024-03-19 20:33 UTC, k0st1a commented on internal/handlers/json/handlers.go
> +	ct := r.Header.Get(headerContentType)
Поправил, сделал облегчённую версию. Middleware параметризуемую Content-Type сделать не получилось.

2024-03-21 09:57 UTC, valentinsoe approved these changes
Спасибо за исправления!

2024-03-21 09:57 UTC, valentinsoe commented on internal/utils/retry.go
> +func (r *retry) Retry(ctx context.Context, fnc func() error) error {
(не для исправления, а мысли вслух)
Для полной универсальности сюда можно еще передавать функцию isConnectionError, то есть чтобы можно было использовать вообще в любых задачах, и чтобы "пользователь" пакета retry мог передать при каких ошибках нужно повторять, а при каких -нет

2024-03-23 13:43 UTC, k0st1a commented on internal/utils/retry.go
> +func (r *retry) Retry(ctx context.Context, fnc func() error) error {
Поправил.

2024-03-23 13:47 UTC, merged