Iter15
k0st1a/metrics pull request #14
Opened 2024-03-31 13:43 UTC by k0st1a

## Итерация 15

Перепланируйте архитектуру агента таким образом, чтобы сбор метрик (опрос runtime) и их отправка осуществлялись в разных горутинах. При этом количество одновременно исходящих запросов на сервер нужно ограничивать «сверху».

Соответствующее значение должно задаваться аргументами:
* Через флаг `-l=<ЗНАЧЕНИЕ>` и переменную окружения `RATE_LIMIT`.

Совет:
* Используйте паттерн worker pool.

Добавьте ещё одну горутину, которая будет использовать пакет [gopsutil](https://github.com/shirou/gopsutil) и собирать дополнительные метрики типа `gauge`:
* `TotalMemory`,
* `FreeMemory`,
* `CPUutilization1` (точное количество — по числу CPU, определяемому во время исполнения).

2024-04-02 23:18 UTC, valentinsoe requested changes
Спасибо за работу!
Написал комментарии по коду.
Текущий подход к накоплению метрик не удачный. Мы многократно отправим значения(перетирая их многократно на сервере).
И для Gauge это не критично,а вот значения Counter будут расти сильно быстрее чем надо.

2024-04-02 23:18 UTC, valentinsoe commented on internal/agent/agent.go
> +				acc = append(acc, gm...)
Такая логика аккумуляции может привести к:
1) очень большому массиву, если reportInterval >> pollInterval
2) При отправке counter - он добавится на сервере много раз:)

2024-04-07 21:12 UTC, k0st1a commented on internal/agent/agent.go
> +				acc = append(acc, gm...)
Поправил.

2024-04-09 22:43 UTC, valentinsoe approved these changes
Спасибо за исправления!

2024-04-17 06:03 UTC, merged